name: charmeznous_by_diakite_tech
description: "Une application de rencontre de haute qualité."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  provider: ^6.1.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  flutter_chat_ui: ^1.6.10
  intl: ^0.19.0
  http: ^1.2.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_female_profile.png
    - assets/images/default_male_profile.png
