// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM7309HMyE_KvPmpyu6OYqRo5DXDDiUd8',
    appId: '1:195138511967:web:aaf8d0b9be5c24c89ee7ea',
    messagingSenderId: '195138511967',
    projectId: 'charmeznous-3d3b8',
    authDomain: 'charmeznous-3d3b8.firebaseapp.com',
    storageBucket: 'charmeznous-3d3b8.appspot.com',
    measurementId: 'G-J0K660ZKQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDElFCUJn9GSptp_lU8i-keZcRYEtGGBpQ',
    appId: '1:195138511967:android:3746883c2f9585cf9ee7ea',
    messagingSenderId: '195138511967',
    projectId: 'charmeznous-3d3b8',
    storageBucket: 'charmeznous-3d3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Jf6dq_p87ha9BT5PLBGThbYSExvaJIY',
    appId: '1:195138511967:ios:9efde9be4d68f5149ee7ea',
    messagingSenderId: '195138511967',
    projectId: 'charmeznous-3d3b8',
    storageBucket: 'charmeznous-3d3b8.appspot.com',
    iosBundleId: 'com.example.charmeznousByDiakite',
  );
}
